### ISSUE TITLE
:NumbersToggle then insert mode changes normal mode numbering

### ISSUE THREAD

**Issue by panozzaj** [myusuf3/numbers.vim#8]
If I am in relative numbers in normal mode, and I invoke :NumbersToggle, I get absolute numbers. If I then go to insert mode and escape, I am back to relative numbers in normal mode. I would have expected to stay in absolute numbers in normal mode. As it stands, I have to enter :NumbersToggle (or a shortcut that runs this) every time I escape from insert mode, it appears.

**Comment by N4M3Z** [comment]
I have the opposite problem in neovim, it does not go back to relative when I return from insert mode to normal mode. Is this expected?

**Comment by N4M3Z** [comment]
Still an issue but only limited to neovim. Is it not supported?
